In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Completer.use_jedi = False
import numpy as np

In [7]:
arr = np.arange(32)
print(arr)
print(len(arr))
print(type(type))
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
32
<class 'type'>
(32,)


In [10]:
# reshape() 메소드 numpy 배열의 차원을 변경한다 => 전체 데이터 개수가 같아야 한다 .
v = arr.reshape(4,2,4)
print(v)
print(v.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
(4, 2, 4)


<img src="./images/shape1.png" align="left" width="600"/>        

<img src="./images/shape2.png" align="left" width="600"/>        

numpy의 sum이라는 메소드 작동방식

In [14]:
# sum() 메소드의 axis 속성의 기본값은 None이고 axis는 대상 차원보다 작은 값을 설정한다.
# 위의 예에서는 데이터의 차원이 3이기 때문에 axis 속성은 2까지 지정할 수 있다.
print(v.ndim)

3


In [21]:
# axis=None
# axis를 기본값으로 실행하면 대상 데이터의 모든 요소의 합계를 리턴한다. => 면, 행, 열을 구분하지 않는다.
# 대상 데이터에 포함된 모든 요소 를 단순히 합산하는 연산이 실행된다.
print(v.shape)
print(v.sum())
print(v.sum(axis=None))

(4, 2, 4)
496
496


In [20]:
total = 0

for i in range(32):
    total += i
print(total)

496


In [25]:
# axis=0
# axis=0은 x축을 기준으로 계산한 합계를 리턴한다.
# shape이 (4,2,4)인 데이터를 x축을 기준으로 계산하면 면이 제거되고 shape은 (2,4)가리턴된다.
res = v.sum(axis=0)
print(res.shape)
print(res.ndim)
print(res)

(2, 4)
2
[[48 52 56 60]
 [64 68 72 76]]


<img src="./images/shape3.png" align="left" width="800"/>        

<img src="./images/shape4.png" align="left" width="700"/>        

In [28]:
# axis = 1
# axis = 1 은 y축
# shape이 (4,2,4)인 데이터를 y축 을 기준으로 계산하면 행이 제거 되고 shape은 (4,4)가 리턴된다.
res = v.sum(axis=1)
print(res.shape)
print(res.ndim)
print(res)

(4, 4)
2
[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]


<img src="./images/shape5.png" align="left" width="700"/>        

<img src="./images/shape6.png" align="left" width="700"/>        

In [29]:
# axis =2 
# axis =2 은 z 축을 기준으로 계산한 합계를 리턴한다 
# shape이 (4,2,4)  인 데이터를 z 축을 기준으로 계산하면 열이 제거되고 shape은 (4,2)가 리턴된다.
res = v.sum(axis=2)
print(res.shape)
print(res.ndim)
print(res)

(4, 2)
2
[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]


<img src="./images/shape7.png" align="left" width="700"/>        

<img src="./images/shape8.png" align="left" width="700"/>        