In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Completer.use_jedi = False
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr, sep='')

인덱싱  
   
배열의 각 요소는 axis 인덱스 배열로 참조할 수 있다.  
1차원 배열은 1개의 인덱스, 2차원 배열은 2개의 인덱스, 3차원 배열은 3개의 인덱스로 요소를 참조할 수 있다.  
인덱싱 작업시[행][열]과 같이 인덱스를 지정하거나 [행,열] 과 같이 인덱스를 지정할 수 있다.

In [2]:
a = np.arange(24) # 1 차원 배열
pprint(a)
b = np.arange(24).reshape(4,6) # 2차원 배열
pprint(b)
c = np.arange(24).reshape(2,4,3) # 3차원 배열
pprint(c)

type: <class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype: int32
numpy 배열의 데이터
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열의 데이터
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [3]:
# 1차원 배열 요소 참조 및 변경
print(a[5])
a[5] = 100000
pprint(a)

5
type: <class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype: int32
numpy 배열의 데이터
[     0      1      2      3      4 100000      6      7      8      9
     10     11     12     13     14     15     16     17     18     19
     20     21     22     23]


In [4]:
# 2차원 배열 요소 참조 및 변경
print(b[0][1])
b[0][1] = 1000000
pprint(b)
print(b[1,3])
b[1,3] = 20000000
pprint(b)

1
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[      0 1000000       2       3       4       5]
 [      6       7       8       9      10      11]
 [     12      13      14      15      16      17]
 [     18      19      20      21      22      23]]
9
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[       0  1000000        2        3        4        5]
 [       6        7        8 20000000       10       11]
 [      12       13       14       15       16       17]
 [      18       19       20       21       22       23]]


In [5]:
# 3차원 배열 요소 참조 및 변경
print(c[1][0][1])
c[1][0][1] = 999999
pprint(c)
print(c[0,2,1])
c[0,2,1] = 777777
pprint(c)

13
type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열의 데이터
[[[     0      1      2]
  [     3      4      5]
  [     6      7      8]
  [     9     10     11]]

 [[    12 999999     14]
  [    15     16     17]
  [    18     19     20]
  [    21     22     23]]]
7
type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열의 데이터
[[[     0      1      2]
  [     3      4      5]
  [     6 777777      8]
  [     9     10     11]]

 [[    12 999999     14]
  [    15     16     17]
  [    18     19     20]
  [    21     22     23]]]


슬라이싱

In [6]:
print(a)
print(a[2:6])

[     0      1      2      3      4 100000      6      7      8      9
     10     11     12     13     14     15     16     17     18     19
     20     21     22     23]
[     2      3      4 100000]


<img src="./images/numpyImage06.jpg" align="left" width="900">

In [7]:
pprint(b)
print('=' * 80)
print(b[1:3])# 열을 생략하면 행 단위의 슬라이싱을 할수 있다.
#print(b[1:3,:])
print('='*80)
print(b[:,1:5])# 열 단위로 슬라이싱 ㅎ려면 행 위치에 반드시 ':'을 적어야 한다. ':'는 전체 행을 의미한다.
print('='*80)
print(b[1:3][1:5]) # b[1:3]로 슬라이싱한 결과에서 [1:5]로 슬라이싱한다.

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[       0  1000000        2        3        4        5]
 [       6        7        8 20000000       10       11]
 [      12       13       14       15       16       17]
 [      18       19       20       21       22       23]]
[[       6        7        8 20000000       10       11]
 [      12       13       14       15       16       17]]
[[ 1000000        2        3        4]
 [       7        8 20000000       10]
 [      13       14       15       16]
 [      19       20       21       22]]
[[12 13 14 15 16 17]]


<img src="./images/numpyImage07.jpg" align="left" width="900">

In [8]:
# 음수 인덱싱을 이용한 범위 설정
# 음수 인덱스는 지정한 axis 의 마지막 요소부터 반대 방향 인덱스 이고 -1은 마지막 요소의 인덱스르르 의미한다.
print(b[1:3,1:5])
print(b[1:-1,1:-1])

[[       7        8 20000000       10]
 [      13       14       15       16]]
[[       7        8 20000000       10]
 [      13       14       15       16]]


In [9]:
# 슬라이싱을 이용한 데이터 수정
pprint(b)
print('=' * 80)
# 슬라이싱을 이용한 배열 생성
slide_arr = b[1:3,1:5]
print(slide_arr)
print('=' *80)
print(slide_arr[:,1:3])
slide_arr[:,1:3] = 999999
print(slide_arr)
print(b)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[       0  1000000        2        3        4        5]
 [       6        7        8 20000000       10       11]
 [      12       13       14       15       16       17]
 [      18       19       20       21       22       23]]
[[       7        8 20000000       10]
 [      13       14       15       16]]
[[       8 20000000]
 [      14       15]]
[[     7 999999 999999     10]
 [    13 999999 999999     16]]
[[      0 1000000       2       3       4       5]
 [      6       7  999999  999999      10      11]
 [     12      13  999999  999999      16      17]
 [     18      19      20      21      22      23]]


불린 인덱싱  
  
numpy의 불린 인덱싱인 배열의 각 요소 선택 여부를 True, False로 지정하는 방식이다. => True가 선택된다.


In [10]:
a = np.arange(24).reshape(4,6)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


a 배열에서 요소의 값이 짝수인 요소의 전체 합계

In [11]:
# a 배열에서 요소의 값이 짝수인 요소의 전체 합계 
# numpy의 브로드 캐스팅 기능을 이용해서 배열의 요소 중에서 짝수인 요소를 확인한다.
even_arr = a % 2 # 브로드 캐스팅 
print(even_arr)
print('='*80)
even_arr2 = a % 2 == 0
print(even_arr2)

[[0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]]
[[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]


In [12]:
# 불린 인덱싱은 브로드캐스팅 결과가 True인 요소들만 추출한다
print(a[even_arr2])
print(a[a % 2 ==0])

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [13]:
print(np.sum(a))
print(a[a % 2 == 0 ].sum())
print(np.sum(a[a %2 == 0]))
print(np.sum(a[a %2 == 1]))
print(np.sum(a[a %2 != 0]).sum())

276
132
132
144
144


In [64]:
print(np.sum(a))
print(a[a % 2 == 0].sum())
print(np.sum(a[a % 2 == 0]))
print(a[a % 2 == 1].sum())
print(np.sum(a[a % 2 !== 0]))

300
156
156
144


불린 인덱싱 응용  
  
데이터 파일 => 2014년 시애틀 강수량 데이터 => ./data/Seattle2014.csv  
2014년 1월 시애틀 평균 강수량

In [15]:
import pandas as pd

In [16]:
# pandas의 read_csv() 메소드로 csv 파일을 읽어서 데이터 프레임으로 리턴한다.
rain_in_seattle = pd.read_csv('./data/Seattle2014.csv')
print(type(rain_in_seattle))
rain_in_seattle

<class 'pandas.core.frame.DataFrame'>


STATION                                STATION_NAME      DATE  \
0    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140101   
1    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140102   
2    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140103   
3    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140104   
4    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140105   
..                 ...                                         ...       ...   
360  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141227   
361  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141228   
362  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141229   
363  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141230   
364  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141231   

     PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  WDF5  WSF2  WSF5  WT01  WT05  \
0       0     0     0    72    33    12   340   310    36    40 -9999 -9999   
1      41     0     0   106    61    32   190   200    94   116 -9999 -9999   
2      15     0     0    89    28    26    30    50    63    72     1 -9999   
3       0     0     0    78     6    27    40    40    45    58     1 -9999   
4       0     0     0    83    -5    37    10    10    67    76 -9999 -9999   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
360    33     0     0    94    44    49   210   210   112   161     1 -9999   
361    41     0     0    67    28    18    50    30    58    72     1 -9999   
362     0     0     0    61     6    43   350   350    76   103     1 -9999   
363     0     0     0    33   -21    36    90    70    63    76 -9999 -9999   
364     0     0     0    33   -27    30    30 -9999    58 -9999 -9999 -9999   

     WT02  WT03  
0   -9999 -9999  
1   -9999 -9999  
2   -9999 -9999  
3   -9999 -9999  
4   -9999 -9999  
..    ...   ...  
360 -9999 -9999  
361 -9999 -9999  
362 -9999 -9999  
363 -9999 -9999  
364 -9999 -9999  

[365 rows x 17 columns]

In [17]:
# 2014년 시애틀 강수량 데이터의 강수량 열(PRCP)의 데이터만 추출한다 .
# 데이터 프레임의 특정 열 1개(시리즈) 추출하기 
#      => 데이터프레임이름['열이름'], 데이터 프레임 이름.get('열이름') , 데이터 프레임이름.열이름
#rain_arr = rain_in_seattle['PRCP']
#rain_arr = rain_in_seattle.get('PRCP')
rain_arr = rain_in_seattle.PRCP
print(type(rain_arr)) # <class 'pandas.core.series.Series'> => 데이터 프레임을 구성하는 열 1개
print(rain_arr)

<class 'pandas.core.series.Series'>
0       0
1      41
2      15
3       0
4       0
       ..
360    33
361    41
362     0
363     0
364     0
Name: PRCP, Length: 365, dtype: int64


In [18]:
# 데이터만 얻어오기 위해서는 values 속성을 사용 
#rain_arr = rain_in_seattle['PRCP'].values
#rain_arr = rain_in_seattle.get('PRCP').values
rain_arr = rain_in_seattle.PRCP.values
print(rain_arr)
print('data size : ',len(rain_arr))

[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23  20   0   0   0   0
   0   0  51   5 183 170  46  18  94 117 264 145 152  10  30  28  25  61
 130   3   0   0   0   5 191 107 165 467  30   0 323  43 188   0   0   5
  69  81 277   3   0   5   0   0   0   0   0  41  36   3 221 140   0   0
   0   0  25   0  46   0   0  46   0   0   0   0   0   0   5 109 185   0
 137   0  51 142  89 124   0  33  69   0   0   0   0   0 333 160  51   0
   0 137  20   5   0   0   0   0   0   0   0   0   0   0   0   0  38   0
  56   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  18  64   0   5  36  13   0   8   3   0   0   0   0   0   0  18  23   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   3 193   0   0   0   0   0   0   0   0   0   5   0   0
   0   0   0   0   0   0   5 127 216   0  10   0   0   0   0   0   0   0
   0   0   0   0   0   0   0  84  13   0  30   0   

In [19]:
days_arr = np.arange(365) # 날짜 배열 
print(days_arr[:40])
# 1월의 날 수 만큼 불린 인덱스를 생성한다. 
condition_jan = days_arr < 31
print(condition_jan[:40])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False]


In [20]:
# 불린 인덱싱을 이용해서 1월의 강수량만 추출한다.
rain_jan = rain_arr[condition_jan]
print(rain_jan) # 1월 강수량
print(len(rain_jan))
print(rain_jan.sum())

[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]
31
940


In [21]:
print('1월 강수량 합계 {}'.format(np.sum(rain_jan)))
print('1월 강수량 평균 {:4.1f}'.format(np.mean(rain_jan)))

1월 강수량 합계 940
1월 강수량 평균 30.3


팬시 인덱싱  
  
배열에 인덱스 배열을 전달해 요소를 참조하는 방법이다.

In [22]:
a = np.arange(1,25).reshape(4,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [23]:
print(a[0,0],a[1,1],a[2,2],a[3,3])
arr = a[0,0], a[1,1], a[2,2], a[3,3]
print(type(arr))
print(arr)
arr = [a[0,0], a[1,1], a[2,2], a[3,3]]
print(type(arr))
print(arr)
print('='*80)

print(a[[0,1,2,3],(0,1,2,3)])

1 8 15 22
<class 'tuple'>
(1, 8, 15, 22)
<class 'list'>
[1, 8, 15, 22]
[ 1  8 15 22]


배열 변환  
  
배열을 변환하는 방법은 전치 , 배열의 shape 변경, 배열 요소 추가 , 배열 결합, 배열 분리 등이 있다.  

전치는 행렬의 인덱스가 바뀌는 변환이다.

<img src="./images/numpyImage08.jpg" align="left" width="300">

In [24]:
# numpy에서 행렬 전치하기 위해서 넘파이배열.T 속성을 사용한다 . 
a = np.random.randint(1,10,(3,2))
print(a)
print(a.T)

[[4 3]
 [1 7]
 [1 6]]
[[4 1 1]
 [3 7 6]]


배열의 shape 변경  

numpy는 배열의 형태를 변경하는 reshape() 메소드와 ravel() 메소드를 제공한다 .  
reshape() 메소드는 데이터 변경없이 지정한 shape으로 배열의 형태를 변환하지만 ravel() 메소드는 배열의 shape을 무조건 1차원으로 변환한다.

In [25]:
a = np.random.randint(1,10,(2,6))
print(a)
print(np.resize(a,(6,2))) # shape이 변경된 결과를 리턴한다.
print(a)
b = np.resize(a,(6,2))
print(b)

[[8 3 1 8 1 9]
 [7 5 1 8 8 8]]
[[8 3]
 [1 8]
 [1 9]
 [7 5]
 [1 8]
 [8 8]]
[[8 3 1 8 1 9]
 [7 5 1 8 8 8]]
[[8 3]
 [1 8]
 [1 9]
 [7 5]
 [1 8]
 [8 8]]


In [26]:
a = np.random.randint(1,10,(2,6))
print(a)
print(a.resize(6,2)) # None

[[9 8 1 6 2 9]
 [7 5 4 8 7 1]]
None


In [27]:
a = np.random.randint(1,10,(3,2))
print(a)
print(a.ravel()) # 1차원으로 변경된 결과를 리턴한다.
print(a)

[[3 4]
 [5 7]
 [9 2]]
[3 4 5 7 9 2]
[[3 4]
 [5 7]
 [9 2]]


resize() 메소드로 배열의  shape과 크리를 변경할 수 있다 .   
넘파이 배열.resize(new_shape), np.resize(넘파이 배열, new_shape)  
resize() 메소드와 reshape() 메소드는 shape을 변경하는 부분에서는 유사하지만 reshape() 메소드는 배열을 구성하는 요소의 개수를 변경하지 못하는 반면에 resize() 메소드는 shape을 변경하는 과정중에서 배열을 구성하는 요소의 개수를 줄이거나 늘릴 수 있다 . 

In [28]:
# ravel() 메소드는 원본 배열의 view를 반환한다.
# ravel() 메소드가 반환한 배열을 수정하면 원본 배열의 내용이 같이 수정된다.
b = a.ravel()
print(b)
b[4] = 999
print(b)
print(a)

[3 4 5 7 9 2]
[  3   4   5   7 999   2]
[[  3   4]
 [  5   7]
 [999   2]]


In [29]:
# reshape() 메소드는 원본 배열의 view를 반환한다.
# reshape() 메소드가 반환한 배열을 수정하면 원본 배열의 내용이 같이 수정된다.
a = np.random.randint(1,10,(2,3))
print(a)
b = a.reshape(3,2,1)
print(b)
b[0][0][0] = 999
print(b)
print(a)

[[8 5 5]
 [9 6 6]]
[[[8]
  [5]]

 [[5]
  [9]]

 [[6]
  [6]]]
[[[999]
  [  5]]

 [[  5]
  [  9]]

 [[  6]
  [  6]]]
[[999   5   5]
 [  9   6   6]]


In [30]:
# 요소의 크기가 변경되는 resize() 메소드 
a = np.random.randint(1,10,(2,6))
print(a)
# a. reshape(2,10) # reshape() 메소드는 원본과 요소의 개수를 다르게 지정하면 에러가 발생한다 . 
a.resize(2,10) # 배열 요소의 개수가 12개에서 20개로 늘어나고 늘어난 요소에는 0이 채워진다.
print(a)
a.resize(2,4) # 배열 요소의 개수가 20 개에서 8개로 줄어들고 줄어든 요소의 데이터는 분실된다.
print(a)

[[3 8 5 2 7 8]
 [1 5 7 2 4 6]]
[[3 8 5 2 7 8 1 5 7 2]
 [4 6 0 0 0 0 0 0 0 0]]
[[3 8 5 2]
 [7 8 1 5]]


In [31]:
a= np.random.randint(1,10,(2,6))
print(a)
a = np.resize(a,(2,10)) # 배열 요소의 개수가 12개에서 20개로 늘어나고 늘어난 요소에는 원본 배열 데이터가 반복되서 채워진다 . 
print(a)
a = np.resize(a,(2,4)) # a.resize(2,4)와 같이 줄어든 요소의 데이터는 분실된다.
print(a)

[[3 6 1 2 6 9]
 [1 1 7 6 5 8]]
[[3 6 1 2 6 9 1 1 7 6]
 [5 8 3 6 1 2 6 9 1 1]]
[[3 6 1 2]
 [6 9 1 1]]


append() 메소드는 배열 끝에 데이터(배열)를 추가한다. axis로 데이터가 추가되는 방향을 지정할 수 있다.  
np.append(넘파이 배열, 추가할 넘파이 배열, axis)


In [32]:
a = np.random.randint(1,10,(3,3))
print(a)
b = np.random.randint(10,19,(3,3))
print(b)

[[3 2 8]
 [7 7 1]
 [1 2 8]]
[[11 18 14]
 [18 17 13]
 [14 11 11]]


In [33]:
# axis=None
# axis를 지정하지 않았을 경우 배열은 1차원으로 변환되서 결합된다. 
print(np.append(a,b))
result = np.append(a,b)
print(result)
result = np.append(a,b , axis =None)
print(result)

[ 3  2  8  7  7  1  1  2  8 11 18 14 18 17 13 14 11 11]
[ 3  2  8  7  7  1  1  2  8 11 18 14 18 17 13 14 11 11]
[ 3  2  8  7  7  1  1  2  8 11 18 14 18 17 13 14 11 11]


In [34]:
# axis = 0
print(np.append(a,b,axis=0)) # a 배열 아래쪽(열방향)에 b 배열이 추가된다.

[[ 3  2  8]
 [ 7  7  1]
 [ 1  2  8]
 [11 18 14]
 [18 17 13]
 [14 11 11]]


In [35]:
# axis=0 인 경우 두 배열이 행의 개수는 달라도 상관이없지만 열의 개수는 반드시 같아야 한다.
diff_shape = np.random.randint(10,19,(4,3)) #a 배열과 열의 개수는 같지만 행의 개수가 다른 배열
print(diff_shape)
print(np.append(a, diff_shape, axis=0))

#diff_shape = np.random.randint(10,19,(3,4)) # a 배열과 행의 개수는 같지만 열의 개수가 다른 배열
#print(diff_shape)
#print(np.append(a,diff_shape,axis=0)) # 추가하려는 배열 diff_shape과 원본 배열 a의 열의 개수가 달라서 에러가 발생된다.

[[13 11 17]
 [10 11 18]
 [13 16 11]
 [11 15 17]]
[[ 3  2  8]
 [ 7  7  1]
 [ 1  2  8]
 [13 11 17]
 [10 11 18]
 [13 16 11]
 [11 15 17]]


In [36]:
# axis = 1
print(np.append(a,b,axis=1)) # a 배열 오른쪽(행방향)에 b 배열이 추가된다.

[[ 3  2  8 11 18 14]
 [ 7  7  1 18 17 13]
 [ 1  2  8 14 11 11]]


In [37]:
# axis=1 인 경우 두 배열의 열의 개수는 달라도 상관없지만 행의 개수는 반드시 같아야한다.
#diff_shape = np.random.randint(10,19,(4,3)) #a 배열과 열의 개수는 같지만 행의 개수가 다른 배열
#print(diff_shape)
#print(np.append(a, diff_shape, axis=1)) # 추가하려는 배열 diff_shape과 원본 배열 a의 행의 개수가 달라서 에러가 발생된다.

diff_shape = np.random.randint(10,19,(3,4)) # a 배열과 행의 개수는 같지만 열의 개수가 다른 배열
print(diff_shape)
print(np.append(a,diff_shape,axis=1)) 

[[17 10 16 11]
 [18 11 12 13]
 [16 11 14 14]]
[[ 3  2  8 17 10 16 11]
 [ 7  7  1 18 11 12 13]
 [ 1  2  8 16 11 14 14]]


insert() 메소드는 지정한 index에 데이터를 삽입한다. axis로 데이터가 삽입되는 방향을 지정할수 있다 .  
np.insert(넘파이 배열, 삽입할 index ,삽입할 데이터, axis)

In [38]:
a = np.random.randint(1, 10,(3,3))
print(a)

[[5 4 7]
 [6 6 5]
 [3 8 2]]


In [39]:
# axis 를 지정하지 않으면 None이 기본값이고 배열을 1차원으로 변환한 후 지정된 index에 데이터를 삽입한다.
print(np.insert(a, 1, 99999))
print(np.insert(a, 1, 99999,axis=None))

[    5 99999     4     7     6     6     5     3     8     2]
[    5 99999     4     7     6     6     5     3     8     2]


In [40]:
# axis=0으로 지정하면 각 열의 열 방향 index에 데이터를 삽입한다.
print(np.insert(a,1,99999,axis=0))

[[    5     4     7]
 [99999 99999 99999]
 [    6     6     5]
 [    3     8     2]]


In [41]:
# axis=1으로 지정하면 각 행의 행 방향 index에 데이터를 삽입한다.
print(np.insert(a,1,99999,axis=1))

[[    5 99999     4     7]
 [    6 99999     6     5]
 [    3 99999     8     2]]


delete() 메소드는 지정한 index의 데이터를 삭제한다. axis로 데이터가 삭제되는 방향을 지정할 수 있다 .  
np.delete(넘파이 배열, 삭제할 index, axis)

In [42]:
a = np.random.randint(1, 10,(3,3))
print(a)

[[8 7 8]
 [4 9 9]
 [3 2 9]]


In [43]:
# axis 를 지정하지 않으면 None이 기본값이고 배열을 1차원으로 변환한 후 지정된 index의 데이터를 삭제한다.
print(np.delete(a, 1))
print(np.delete(a, 1,axis=None))

[8 8 4 9 9 3 2 9]
[8 8 4 9 9 3 2 9]


In [44]:
# axis=0으로 지정하면 각 열의 열 방향 index의 데이터를 삭제한다.
print(np.delete(a,1,axis=0))

[[8 7 8]
 [3 2 9]]


In [45]:
# axis=1으로 지정하면 각 행의 행 방향  index의 데이터를 삭제한다.
print(np.delete(a,1,axis=1))

[[8 8]
 [4 9]
 [3 9]]


배열 결합  

numpy는 배열과 배열을 결합하는 concatenate(), vstack(), hstack() 메소드를 제공한다.

concatenate() 메소드는 axis 로 결합할 방향을 지정해서 배열을 결합한다.   
np.concatenate((배열1, 배열2, ..... ), axis)  


In [46]:
a = np.random.randint(1,10,(2,3))
print(a)
b = np.random.randint(10,19,(2,3))
print(b)

[[3 8 9]
 [6 8 5]]
[[15 14 17]
 [17 15 12]]


In [47]:
# axis 를 None으로 지정하면 1차원 배열로 변환한 후 배열을 결합한다.
print(np.concatenate((a,b),axis=None))

[ 3  8  9  6  8  5 15 14 17 17 15 12]


In [48]:
# axis를 지정하지 않으면 0이 기본값이고 아래쪽으로 배열을 결합한다. 결합하려는 배열들의 열의 개수가 다르면 에러가 발생된다.
print(np.concatenate((a,b)))
print('='*80)
print(np.concatenate((a,b),axis=0))
print('='*80)
print(np.concatenate([a,b],axis=0))


[[ 3  8  9]
 [ 6  8  5]
 [15 14 17]
 [17 15 12]]
[[ 3  8  9]
 [ 6  8  5]
 [15 14 17]
 [17 15 12]]
[[ 3  8  9]
 [ 6  8  5]
 [15 14 17]
 [17 15 12]]


In [49]:
#  axis를 1로 지정하면 오른쪽으로 배열을 결합한다. 결합하려는 배열들의 행의 개수가 다르면 에러가 발생된다. 
print(np.concatenate((a,b),axis= 1))

[[ 3  8  9 15 14 17]
 [ 6  8  5 17 15 12]]


vstack() 메소드는 인수로 지정된 배열을 수직 방향(axis=0) 으로 결합한다.  
np.concatenate((배열1, 배열2, ...), axis=0)와 동일한 기능을 실행한다.  
np.vstack((배열1, 배열2, ...))  

In [50]:
a = np.random.randint(1,10,(2,3))
print(a)
b = np.random.randint(10,19,(2,3))
print(b)

[[6 4 3]
 [7 7 6]]
[[16 12 17]
 [16 16 12]]


In [51]:
print(np.vstack((a,b))) # 결합할 배열들의 열의 개수가 다르면 에러가 발생된다.

[[ 6  4  3]
 [ 7  7  6]
 [16 12 17]
 [16 16 12]]


hstack() 메소드는 인수로 지정된 배열을 수평 방향(axis=1) 으로 결합한다.  
np.concatenate((배열1, 배열2, ...), axis=1)와 동일한 기능을 실행한다.  
np.hstack((배열1, 배열2, ...))

In [52]:
print(np.hstack((a,b))) # 결합할 배열들의 행의 개수가 다르면 에러가 발생된다.

[[ 6  4  3 16 12 17]
 [ 7  7  6 16 16 12]]


배열 분리  

numpy는 배열을 수직(열) 방향으로 분할하는 hsplit() 메소드와 수평(행) 방향으로 분할하는 hsplit() 메소드를 제공한다.

In [53]:
a = np.arange(1,25).reshape(4,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


hsplit() 메소드로 배열을 수평 방향으로 분할한다.  
np.hsplit(넘파이 배열, 분할할 개수)

In [54]:
result = np.hsplit(a,2) # 함수의 실행 결과 리턴값은 numpy 배열이 저장된 파이썬 list 형태이다.
print(type(result))
print(result)
print(type(result[0]))
print(result[0])
print(result[1])

<class 'list'>
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
<class 'numpy.ndarray'>
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]
[[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]]


<img src="./images/numpyImage09.jpg" align="left" width="800">

In [55]:
result = np.hsplit(a,3)
print(result)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


<img src="./images/numpyImage10.jpg" align="left" width="800">

In [56]:
result = np.hsplit(a,6)
print(result)

[array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2],
       [ 8],
       [14],
       [20]]), array([[ 3],
       [ 9],
       [15],
       [21]]), array([[ 4],
       [10],
       [16],
       [22]]), array([[ 5],
       [11],
       [17],
       [23]]), array([[ 6],
       [12],
       [18],
       [24]])]


<img src="./images/numpyImage11.jpg" align="left" width="800">

In [57]:
result = np.hsplit(a,[1,3,5])
print(result)

[array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]]), array([[ 6],
       [12],
       [18],
       [24]])]


vsplit() 메소드로 배열을 수직 방향으로 분할한다. np.vsplit(넘파이 배열, 분할할 개수 

In [58]:
result = np.vsplit(a,2)
print(result)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]


<img src="./images/numpyImage12.jpg" align="left" width="800">

In [59]:
result = np.vsplit(a,4)
print(result)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


<img src="./images/numpyImage13.jpg" align="left" width="800">

In [60]:
result = np.vsplit(a,[1,3])
print(result)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


<img src="./images/numpyImage14.jpg" align="left" width="800">